package airlinereservation;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CHARIF
 */
public class Add_Flights extends javax.swing.JInternalFrame {

    /**
     * Creates new form Add_Flights
     */
    public Add_Flights() {
        initComponents();
        FlightAutoID();
    }

    Connection con;
    PreparedStatement pst;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        flightID = new javax.swing.JLabel();
        flightArriveTime = new javax.swing.JTextField();
        flightName = new javax.swing.JTextField();
        flightDestination = new javax.swing.JComboBox<>();
        flightDepTime = new javax.swing.JTextField();
        flightDepDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        flightArriveDate = new com.toedter.calendar.JDateChooser();
        flightCharges = new javax.swing.JTextField();
        flightSource = new javax.swing.JComboBox<>();
        CloseAddSession = new javax.swing.JButton();
        AddFlightDetails = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1039, 560));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FLIGHT ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 130, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FLIGHT NAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 180, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SOURCE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 230, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DEPARTURE TIME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 290, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DEPARTURE DATE");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 340, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ARRIVE TIME");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 390, 130, 30);

        flightID.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        flightID.setForeground(new java.awt.Color(0, 30, 224));
        flightID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(flightID);
        flightID.setBounds(320, 130, 230, 30);

        flightArriveTime.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        flightArriveTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flightArriveTime);
        flightArriveTime.setBounds(320, 390, 230, 30);

        flightName.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        flightName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flightName);
        flightName.setBounds(320, 180, 230, 30);

        flightDestination.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel1.add(flightDestination);
        flightDestination.setBounds(740, 180, 230, 30);

        flightDepTime.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        flightDepTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flightDepTime);
        flightDepTime.setBounds(320, 290, 230, 30);

        flightDepDate.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel1.add(flightDepDate);
        flightDepDate.setBounds(320, 340, 230, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DESTINATION");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(580, 180, 130, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("FLIGHT CHARGES");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(590, 290, 130, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ARRIVE DATE");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(580, 240, 130, 30);

        flightArriveDate.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel1.add(flightArriveDate);
        flightArriveDate.setBounds(740, 240, 230, 30);

        flightCharges.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        flightCharges.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flightCharges);
        flightCharges.setBounds(740, 290, 230, 30);

        flightSource.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel1.add(flightSource);
        flightSource.setBounds(320, 230, 230, 30);

        CloseAddSession.setBackground(new java.awt.Color(204, 0, 0));
        CloseAddSession.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        CloseAddSession.setText("CLOSE");
        CloseAddSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseAddSessionActionPerformed(evt);
            }
        });
        jPanel1.add(CloseAddSession);
        CloseAddSession.setBounds(860, 450, 120, 40);

        AddFlightDetails.setBackground(new java.awt.Color(153, 255, 204));
        AddFlightDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        AddFlightDetails.setText("ADD");
        AddFlightDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(AddFlightDetails);
        AddFlightDetails.setBounds(680, 450, 120, 40);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 173, 184));
        jLabel7.setText("ADD FLIGHT DETAILS");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(180, 10, 510, 70);

        jLabel12.setBackground(new java.awt.Color(255, 255, 204));
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHARIF\\Downloads\\FlightBaCK1.jpg")); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 1170, 560);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1170, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddFlightDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightDetailsActionPerformed
        // TODO add your handling code here:
        String flID = flightID.getText();
        String flName = flightName.getText();
        String flSource = flightSource.getSelectedItem().toString();
        String fldepTime = flightDepTime.getText();
        
        DateFormat depDate = new SimpleDateFormat("dd-MM-yyyy");
        String fldepDate = depDate.format(flightDepDate.getDate());
        
        DateFormat arrDate = new SimpleDateFormat("dd-MM-yyyy");
        String flarrDate = arrDate.format(flightArriveDate.getDate());
        
        String flarrTime = flightArriveTime.getText();
        String flcharges = flightCharges.getText();
        String flDestination = flightDestination.getSelectedItem().toString();
        
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String query = "insert into flights values(?,?,?,?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");
            pst = con.prepareStatement(query);
            
            pst.setString(1, flID);
            pst.setString(2, flName);
            pst.setString(3,flSource);
            pst.setString(4,fldepTime);
            pst.setString(5,fldepDate);
            pst.setString(6,flarrTime);
            pst.setString(7,flDestination);
            pst.setString(8,flarrDate);
            pst.setString(9,flcharges);
           
          
           pst.executeUpdate();
           
           JOptionPane.showMessageDialog(null,"......."+"the " + flName + " flight has been added");
           
             flightID.setText("");
            flightName.setText("");
            flightSource.setSelectedIndex(0);
            flightDepTime.setText("");
            flightDepDate.setDate(null);
            flightArriveTime.setText("");
            flightDestination.setSelectedIndex(0);
            flightArriveDate.setDate(null);
            flightCharges.setText("");
            FlightAutoID();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Add_Flights.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Add_Flights.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddFlightDetailsActionPerformed

    private void CloseAddSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseAddSessionActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this,"Do you want to close add Flight session session ?"," Confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
       if(res == JOptionPane.YES_OPTION){
           // closing the system
           this.hide();
       } else if(res == JOptionPane.NO_OPTION || res == JOptionPane.CLOSED_OPTION){
           return;
       }
    }//GEN-LAST:event_CloseAddSessionActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
         try
        {
             
               
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");

            try
            {
                String q="select * from sourcedestination";
                pst=con.prepareStatement(q);
                ResultSet myresult=pst.executeQuery();
                
                if(myresult.next())
                {
                    do
                    {
                        flightSource.addItem(myresult.getString("sourceflight"));
                        flightDestination.addItem(myresult.getString("flightDestination"));
                    }
                    while(myresult.next());
                }
                 
                FlightAutoID();
                  
                       
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error in query due to"+e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
                }
                finally
                {
                    con.close();
                }
            }
        catch(Exception e)
        {
         e.printStackTrace();
         JOptionPane.showMessageDialog(rootPane, "Error in connection" +e.getMessage());
    }
    }//GEN-LAST:event_formInternalFrameActivated

    
    public void FlightAutoID(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select MAX(flightID) from  flights");
            rs.next();
            rs.getString("MAX(flightID)");
            
            if(rs.getString("MAX(flightID)") == null ){
                 flightID.setText("FL03001");
            }
            else {
                long id = Long.parseLong(rs.getString("MAX(flightID)").substring(2,rs.getString("MAX(flightID)").length()));
                id++;
                flightID.setText("FL" + String.format("%04d", id));
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Add_Flights.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Add_Flights.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFlightDetails;
    private javax.swing.JButton CloseAddSession;
    private com.toedter.calendar.JDateChooser flightArriveDate;
    private javax.swing.JTextField flightArriveTime;
    private javax.swing.JTextField flightCharges;
    private com.toedter.calendar.JDateChooser flightDepDate;
    private javax.swing.JTextField flightDepTime;
    private javax.swing.JComboBox<String> flightDestination;
    private javax.swing.JLabel flightID;
    private javax.swing.JTextField flightName;
    private javax.swing.JComboBox<String> flightSource;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
