/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinereservation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author CHARIF
 */
public class Cancel_seat extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cancel_seat
     */
    public Cancel_seat() {
        initComponents();
    }

    Connection con;
    PreparedStatement pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TicketNmb = new javax.swing.JTextField();
        FlightID = new javax.swing.JTextField();
        custName = new javax.swing.JTextField();
        custID = new javax.swing.JTextField();
        flightSeat = new javax.swing.JTextField();
        SearchCustomerID = new javax.swing.JButton();
        CancelButtonSeat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cancel Seat");

        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Flight ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 270, 140, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ticket Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 320, 140, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Seat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 370, 140, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Customer Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 220, 140, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Customer ID");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 160, 140, 30);

        TicketNmb.setBackground(new java.awt.Color(255, 255, 204));
        TicketNmb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TicketNmb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(TicketNmb);
        TicketNmb.setBounds(180, 320, 270, 30);

        FlightID.setBackground(new java.awt.Color(255, 255, 204));
        FlightID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FlightID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(FlightID);
        FlightID.setBounds(180, 270, 270, 30);

        custName.setBackground(new java.awt.Color(255, 255, 204));
        custName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        custName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(custName);
        custName.setBounds(180, 220, 270, 30);

        custID.setBackground(new java.awt.Color(255, 255, 204));
        custID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        custID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(custID);
        custID.setBounds(180, 160, 270, 30);

        flightSeat.setBackground(new java.awt.Color(255, 255, 204));
        flightSeat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        flightSeat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flightSeat);
        flightSeat.setBounds(180, 370, 270, 30);

        SearchCustomerID.setBackground(new java.awt.Color(0, 204, 204));
        SearchCustomerID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchCustomerID.setText("Search");
        SearchCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCustomerIDActionPerformed(evt);
            }
        });
        jPanel1.add(SearchCustomerID);
        SearchCustomerID.setBounds(470, 160, 73, 30);

        CancelButtonSeat.setBackground(new java.awt.Color(255, 0, 0));
        CancelButtonSeat.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        CancelButtonSeat.setText("Cancel");
        CancelButtonSeat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(CancelButtonSeat);
        CancelButtonSeat.setBounds(500, 420, 130, 50);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHARIF\\Downloads\\Airline\\cancelback.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCustomerIDActionPerformed
        // TODO add your handling code here:
            try{
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");
                
                try
                {
                    String q="select * from tickets where Cust_ID=?";
                    pst=con.prepareStatement(q);
                    pst.setString(1,custID.getText());
                    ResultSet rs=pst.executeQuery();
                     if(rs.next())
                    {
                     
                         custName.setText(rs.getString("CustName")+ " " + rs.getString("Cust_lname"));
                         FlightID.setText(rs.getString("FlightID"));
                         TicketNmb.setText(rs.getString("Ticket_Id"));
                         flightSeat.setText(rs.getString("seats"));
       
                         
                    }
                  else
                     {
                         JOptionPane.showMessageDialog(rootPane, "No Tickets Found for your customerID!!!", "Error",JOptionPane.ERROR_MESSAGE);
                     }
                
                     
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error in query due to"+e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
                }
                finally
                {
                    con.close();
                }
            }
        catch(Exception e)
        {
         e.printStackTrace();
         JOptionPane.showMessageDialog(rootPane, "Error in connection" +e.getMessage());
    }
    }//GEN-LAST:event_SearchCustomerIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButtonSeat;
    private javax.swing.JTextField FlightID;
    private javax.swing.JButton SearchCustomerID;
    private javax.swing.JTextField TicketNmb;
    private javax.swing.JTextField custID;
    private javax.swing.JTextField custName;
    private javax.swing.JTextField flightSeat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
