/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinereservation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author CHARIF
 */
public class Change_Password extends javax.swing.JInternalFrame {

    /**
     * Creates new form Change_Password
     */
    public Change_Password() {
        initComponents();
    }
    Connection con;
    PreparedStatement pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        oldpass = new javax.swing.JPasswordField();
        confirmPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        Update_EmployeePassword = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("CHANGE PASSWORD");

        jPanel1.setLayout(null);

        newPass.setBackground(new java.awt.Color(204, 255, 255));
        newPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(newPass);
        newPass.setBounds(210, 210, 290, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("New Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 210, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Retype Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 260, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Old Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 160, 130, 30);

        oldpass.setBackground(new java.awt.Color(204, 255, 255));
        oldpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(oldpass);
        oldpass.setBounds(210, 160, 290, 30);

        confirmPass.setBackground(new java.awt.Color(204, 255, 255));
        confirmPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(confirmPass);
        confirmPass.setBounds(210, 260, 290, 30);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 153, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Update Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(140, 0, 350, 50);

        Update_EmployeePassword.setBackground(new java.awt.Color(153, 255, 204));
        Update_EmployeePassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Update_EmployeePassword.setText("Update");
        Update_EmployeePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_EmployeePasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Update_EmployeePassword);
        Update_EmployeePassword.setBounds(400, 350, 100, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHARIF\\Downloads\\passchange.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 710, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Update_EmployeePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_EmployeePasswordActionPerformed
        // TODO add your handling code here:
         try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");

            try
            {
                String q="select * from users where password=?";
                pst=con.prepareStatement(q);
                pst.setString(1,oldpass.getText());

                ResultSet myresult=pst.executeQuery();
                if(myresult.next())
                {
                    myglobalclass.upassword=oldpass.getText();
                    if(myglobalclass.upassword.equals(myresult.getString("password")))
                    {
                        String p="update users set password=?";

                        pst=con.prepareStatement(p);
                        pst.setString(1,newPass.getText());
                        if(newPass.getText().equals(confirmPass.getText()))
                        {
                            pst.executeUpdate();
                            JOptionPane.showMessageDialog(rootPane, "password has been changed successfully", "Success",JOptionPane.INFORMATION_MESSAGE);

                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane, "Password isn't retyped correctly", "Error",JOptionPane.ERROR_MESSAGE);
                        }
                        oldpass.setText("");
                            newPass.setText("");
                            confirmPass.setText("");
                    }

                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Old Password isn't correct", "Error",JOptionPane.ERROR_MESSAGE);
                }

                //                    else
                //                    {
                    //
                    //
                    //                             String q2="select * from employeetable where username=? and password=?";
                    //                              PreparedStatement mystatement1=myconnection.prepareStatement(q2);
                    //                          mystatement1.setString(1,jTextField1.getText());
                    //                         mystatement1.setString(2,jPasswordField1.getText());
                    //                           ResultSet myresult1=mystatement1.executeQuery();
                    //                         if(myresult1.next())
                    //                         {
                        //                             myglobalclass.uname=jTextField1.getText();
                        //                          parentframe2 obj=new parentframe2();
                        //                             obj.setExtendedState(MAXIMIZED_BOTH);
                        //                          this.dispose();
                        //                            obj.setVisible(true);
                        //                            }
                    //                             else
                    //                             {
                        //                             JOptionPane.showMessageDialog(rootPane, "Wrong username/passsword", "Error",JOptionPane.ERROR_MESSAGE);
                        //                             }
                    //                    }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error in query due to"+e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
            }
            finally
            {
                con.close();
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error in connection" +e.getMessage());
        }

    }//GEN-LAST:event_Update_EmployeePasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update_EmployeePassword;
    private javax.swing.JPasswordField confirmPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JPasswordField oldpass;
    // End of variables declaration//GEN-END:variables
}
