/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinereservation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author CHARIF
 */
public class CreateNewUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form CreateNewUser
     */
    public CreateNewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserEmail = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        UserPassword = new javax.swing.JPasswordField();
        CancelCreateUser = new javax.swing.JButton();
        CreateButtonUsers = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 150, 130, 30);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 220, 130, 30);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 80, 130, 30);

        UserEmail.setBackground(new java.awt.Color(0, 0, 0));
        UserEmail.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        UserEmail.setForeground(new java.awt.Color(255, 255, 255));
        UserEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(UserEmail);
        UserEmail.setBounds(180, 150, 240, 30);

        userName.setBackground(new java.awt.Color(0, 0, 0));
        userName.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(userName);
        userName.setBounds(180, 80, 240, 30);

        UserPassword.setBackground(new java.awt.Color(0, 0, 0));
        UserPassword.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        UserPassword.setForeground(new java.awt.Color(255, 255, 255));
        UserPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(UserPassword);
        UserPassword.setBounds(180, 220, 240, 30);

        CancelCreateUser.setBackground(new java.awt.Color(255, 0, 0));
        CancelCreateUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CancelCreateUser.setText("Cancel");
        CancelCreateUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CancelCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelCreateUserActionPerformed(evt);
            }
        });
        jPanel1.add(CancelCreateUser);
        CancelCreateUser.setBounds(350, 300, 100, 40);

        CreateButtonUsers.setBackground(new java.awt.Color(128, 179, 151));
        CreateButtonUsers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreateButtonUsers.setText("Create");
        CreateButtonUsers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CreateButtonUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonUsersActionPerformed(evt);
            }
        });
        jPanel1.add(CreateButtonUsers);
        CreateButtonUsers.setBounds(233, 303, 100, 40);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Create New User");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 10, 280, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHARIF\\Downloads\\rsz_user.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 360);

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelCreateUserActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_CancelCreateUserActionPerformed

    private void CreateButtonUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonUsersActionPerformed
        // TODO add your handling code here:
        try
            {
                Connection myconnection;
                Class.forName("com.mysql.jdbc.Driver");
                myconnection=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");
                
                try
                {
                    String q="insert into users(username,email,password)values(?,?,?)";
                    PreparedStatement mystatement=myconnection.prepareStatement(q);
                    mystatement.setString(1,userName.getText());
                    mystatement.setString(2,UserEmail.getText());
                    mystatement.setString(3, UserPassword.getText());
                     mystatement.executeUpdate();
                      JOptionPane.showMessageDialog(rootPane, "An other Admin has been Created", "Success", JOptionPane.INFORMATION_MESSAGE);
                 }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error in query due to"+e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
                }
                finally
                {
                    myconnection.close();
                }
            }
        catch(Exception e)
        {
         e.printStackTrace();
         JOptionPane.showMessageDialog(rootPane, "Error in connection" +e.getMessage());
        }
    }//GEN-LAST:event_CreateButtonUsersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelCreateUser;
    private javax.swing.JButton CreateButtonUsers;
    private javax.swing.JTextField UserEmail;
    private javax.swing.JPasswordField UserPassword;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
