/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinereservation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author CHARIF
 */
public class Delete_Employee extends javax.swing.JInternalFrame {

    /**
     * Creates new form Delete_Employee
     */
    public Delete_Employee() {
        initComponents();
    }
    
    Connection con;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EmailEmployee = new javax.swing.JTextField();
        CloseButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Email");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 180, 130, 40);

        EmailEmployee.setBackground(new java.awt.Color(255, 225, 138));
        EmailEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmailEmployee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(EmailEmployee);
        EmailEmployee.setBounds(250, 180, 370, 40);

        CloseButton.setBackground(new java.awt.Color(255, 0, 0));
        CloseButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CloseButton);
        CloseButton.setBounds(460, 350, 120, 40);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 73, 58));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DELETE AN EMPLOYEE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 0, 570, 80);

        DeleteButton.setBackground(new java.awt.Color(160, 150, 63));
        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButton);
        DeleteButton.setBounds(270, 350, 120, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHARIF\\Downloads\\delEmployeeBack.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(4, 0, 750, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
           this.hide();
       
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        try
        {
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");

            try
            {
                String q="delete from employeedatabase where EmpEmail=?";
                pst=con.prepareStatement(q);
                pst.setString(1,EmailEmployee.getText());
              int a=  JOptionPane.showConfirmDialog(rootPane, "Do you really want to delete?", "Deleting", JOptionPane.YES_NO_OPTION);
               
                if(a==JOptionPane.YES_OPTION)
                {
                    if(!EmailEmployee.getText().equals(""))
                    {
                    pst.executeUpdate();
                    
                          EmailEmployee.setText("");
                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Employee Deleted", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
                    else
                    {
                          JOptionPane.showMessageDialog(rootPane, "Employee Doesnt Exists", "Sorry", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
              
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error in query due to"+e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
            }
            finally
            {
                con.close();
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error in connection" +e.getMessage());
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField EmailEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
