/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinereservation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author CHARIF
 */
public class Enquiry_Tickets extends javax.swing.JInternalFrame {

    /**
     * Creates new form Enquiry_Tickets
     */
    public Enquiry_Tickets() {
        initComponents();
    }
    Connection con;
    PreparedStatement pst;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tickNo = new javax.swing.JTextField();
        custName = new javax.swing.JTextField();
        flightId = new javax.swing.JTextField();
        flightName = new javax.swing.JTextField();
        flSource = new javax.swing.JTextField();
        flightseat = new javax.swing.JTextField();
        depDate = new javax.swing.JTextField();
        custid = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        depTime1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Ticket Enquiry");

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer ID");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 100, 120, 30);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Customer Name");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 150, 120, 30);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Flight ID");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 200, 120, 30);

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Flight Name");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 250, 120, 30);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Flight Source");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 310, 120, 30);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Flight Seat");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 360, 120, 30);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Departure Date");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(530, 50, 120, 30);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Departure Time");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(530, 100, 120, 30);

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ticket Number");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 50, 120, 30);

        tickNo.setBackground(new java.awt.Color(204, 255, 204));
        tickNo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tickNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tickNo);
        tickNo.setBounds(140, 50, 250, 30);

        custName.setBackground(new java.awt.Color(204, 255, 204));
        custName.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        custName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(custName);
        custName.setBounds(140, 150, 250, 30);

        flightId.setBackground(new java.awt.Color(204, 255, 204));
        flightId.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        flightId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flightId);
        flightId.setBounds(140, 200, 250, 30);

        flightName.setBackground(new java.awt.Color(204, 255, 204));
        flightName.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        flightName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flightName);
        flightName.setBounds(140, 250, 250, 30);

        flSource.setBackground(new java.awt.Color(204, 255, 204));
        flSource.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        flSource.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flSource);
        flSource.setBounds(140, 310, 250, 30);

        flightseat.setBackground(new java.awt.Color(204, 255, 204));
        flightseat.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        flightseat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flightseat);
        flightseat.setBounds(140, 360, 250, 30);

        depDate.setBackground(new java.awt.Color(204, 255, 204));
        depDate.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        depDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(depDate);
        depDate.setBounds(680, 50, 250, 30);

        custid.setBackground(new java.awt.Color(204, 255, 204));
        custid.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        custid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(custid);
        custid.setBounds(140, 100, 250, 30);

        searchButton.setBackground(new java.awt.Color(153, 153, 255));
        searchButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchButton.setText("Search");
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton);
        searchButton.setBounds(400, 50, 73, 30);

        CloseButton.setBackground(new java.awt.Color(255, 0, 0));
        CloseButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CloseButton);
        CloseButton.setBounds(840, 360, 100, 40);

        depTime1.setBackground(new java.awt.Color(204, 255, 204));
        depTime1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        depTime1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(depTime1);
        depTime1.setBounds(680, 100, 250, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHARIF\\Downloads\\Airline\\rsz_enqui.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
         try
            {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");
                
                try
                {
                    String q="select * from tickets where Ticket_Id=?";
                    pst=con.prepareStatement(q);
                    pst.setString(1,tickNo.getText());
                    ResultSet rs=pst.executeQuery();
                     if(rs.next())
                    {
                     
                       tickNo.setText(rs.getString("Ticket_Id"));
                        custid.setText(rs.getString("Cust_ID"));
                         custName.setText(rs.getString("CustName")+ " "+rs.getString("Cust_lname"));
                           flightId.setText(rs.getString("FlightID"));
                             flightName.setText(rs.getString("FlightName"));
                              flSource.setText(rs.getString("flightsource"));
                              flightseat.setText(rs.getString("seats"));
                              depDate.setText(rs.getString("depDate"));
                              depTime1.setText(rs.getString("depTime"));
                               JOptionPane.showMessageDialog(rootPane, "Ticket Enquiry Successful..Have a Safe Journey :)", "Success",JOptionPane.INFORMATION_MESSAGE);
                    }
                  else
                     {
                         JOptionPane.showMessageDialog(rootPane, "No Tickets Found for your customerID!!!", "Error",JOptionPane.ERROR_MESSAGE);
                     }
                
                     
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error in query due to"+e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
                }
                finally
                {
                    con.close();
                }
            }
        catch(Exception e)
        {
         e.printStackTrace();
         JOptionPane.showMessageDialog(rootPane, "Error in connection" +e.getMessage());
    }
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JTextField custName;
    private javax.swing.JTextField custid;
    private javax.swing.JTextField depDate;
    private javax.swing.JTextField depTime1;
    private javax.swing.JTextField flSource;
    private javax.swing.JTextField flightId;
    private javax.swing.JTextField flightName;
    private javax.swing.JTextField flightseat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField tickNo;
    // End of variables declaration//GEN-END:variables
}
