/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinereservation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author CHARIF
 */
public class PaymentTickets extends javax.swing.JInternalFrame {

    /**
     * Creates new form PaymentTickets
     */
    public PaymentTickets() {
        initComponents();
    }
    
    Connection con;
    PreparedStatement pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrouppPaymentButton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AmountCash = new javax.swing.JTextField();
        FlightID = new javax.swing.JTextField();
        TicketsID = new javax.swing.JTextField();
        CustID = new javax.swing.JTextField();
        CreditCard = new javax.swing.JRadioButton();
        CashButton = new javax.swing.JRadioButton();
        SearchButtonTicket = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 120, 140, 30);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Flight ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 180, 140, 30);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Amount");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 250, 140, 30);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mode Payment");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 320, 140, 30);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ticket ID");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 50, 140, 40);
        jPanel1.add(AmountCash);
        AmountCash.setBounds(280, 240, 330, 40);
        jPanel1.add(FlightID);
        FlightID.setBounds(280, 170, 330, 40);
        jPanel1.add(TicketsID);
        TicketsID.setBounds(280, 50, 330, 40);
        jPanel1.add(CustID);
        CustID.setBounds(280, 110, 330, 40);

        CreditCard.setBackground(new java.awt.Color(204, 255, 204));
        GrouppPaymentButton.add(CreditCard);
        CreditCard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreditCard.setText("Credit Card");
        jPanel1.add(CreditCard);
        CreditCard.setBounds(320, 290, 130, 40);

        CashButton.setBackground(new java.awt.Color(240, 219, 215));
        GrouppPaymentButton.add(CashButton);
        CashButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CashButton.setText("Cash");
        CashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CashButton);
        CashButton.setBounds(320, 343, 130, 40);

        SearchButtonTicket.setBackground(new java.awt.Color(0, 204, 204));
        SearchButtonTicket.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        SearchButtonTicket.setText("Search");
        SearchButtonTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonTicketActionPerformed(evt);
            }
        });
        jPanel1.add(SearchButtonTicket);
        SearchButtonTicket.setBounds(670, 50, 120, 40);

        SaveButton.setBackground(new java.awt.Color(204, 255, 255));
        SaveButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SaveButton);
        SaveButton.setBounds(580, 350, 120, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHARIF\\Downloads\\100$Background.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 430);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonTicketActionPerformed
        // TODO add your handling code here:
        try
            {
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");
                
                try
                {
                    String q="select * from  tickets where Ticket_Id=?";
                    pst=con.prepareStatement(q);
                    pst.setString(1,TicketsID.getText());
                    ResultSet myresult=pst.executeQuery();
                     if(myresult.next())
                    {
                     
                       CustID.setText(myresult.getString("Cust_ID"));
                        FlightID.setText(myresult.getString("FlightID"));
                       AmountCash.setText(myresult.getString("amount"));
                       
                    }
                  else
                     {
                         JOptionPane.showMessageDialog(rootPane, "Wrong TicketNO/No Records ", " Error ",JOptionPane.ERROR_MESSAGE);
                     }
                
                     
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error in query due to"+e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
                }
                finally
                {
                    con.close();
                }
            }
        catch(Exception e)
        {
         e.printStackTrace();
         JOptionPane.showMessageDialog(rootPane, "Error in connection" +e.getMessage());
    }
    }//GEN-LAST:event_SearchButtonTicketActionPerformed

    private void CashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CashButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        try
            { 
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");
                
                try
                {
                    String q="insert into paymenttickets values(?,?,?,?,?)";
                    pst=con.prepareStatement(q);
                    pst.setString(1,TicketsID.getText());
                    pst.setString(2,CustID.getText());
                    pst.setString(3,FlightID.getText());
                    pst.setString(4,AmountCash.getText());
                
                    if(CreditCard.isSelected())
                   {
                        pst.setString(5, "CREDIT CARD");
                       
                        PayByCredit win = new PayByCredit();
                        JDesktopPane desktopPane = getDesktopPane();
                        desktopPane.add(win);
                        win.show();
                    
                   }
                   else if(CashButton.isSelected())
                   {
                        pst.setString(5, "CASH");
                         JOptionPane.showMessageDialog(rootPane, "PAYMENT SUCCESSFUL", "Payment details", JOptionPane.INFORMATION_MESSAGE);
                         this.dispose();
                          JOptionPane.showMessageDialog(rootPane, "Ticket Booked...Have a Nice Day", "Booking Status", JOptionPane.INFORMATION_MESSAGE);
                   }
                   
                    pst.executeUpdate();
                   
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error in query due to"+e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
                }
                finally
                {
                    con.close();
                }
            }
        catch(Exception e)
        {
         e.printStackTrace();
         JOptionPane.showMessageDialog(rootPane, "Error in connection" +e.getMessage());
    }
    }//GEN-LAST:event_SaveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountCash;
    private javax.swing.JRadioButton CashButton;
    private javax.swing.JRadioButton CreditCard;
    private javax.swing.JTextField CustID;
    private javax.swing.JTextField FlightID;
    private javax.swing.ButtonGroup GrouppPaymentButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton SearchButtonTicket;
    private javax.swing.JTextField TicketsID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
