/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinereservation;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CHARIF
 */
public class ViewFkightInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewFkightInfo
     */
    public ViewFkightInfo() {
        initComponents();
    }

    Connection con;
    PreparedStatement pst;
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        flight_ID = new javax.swing.JTextField();
        flight_Source = new javax.swing.JTextField();
        flight_DepTime = new javax.swing.JTextField();
        flight_ArriveTime = new javax.swing.JTextField();
        flight_Destination = new javax.swing.JTextField();
        flight_Charges = new javax.swing.JTextField();
        flight_Name = new javax.swing.JTextField();
        flight_arriveDate = new com.toedter.calendar.JDateChooser();
        flight_DepDate = new com.toedter.calendar.JDateChooser();
        SearchByIDButton = new javax.swing.JButton();
        SearchByNameButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDisplayFlightByName = new javax.swing.JTable();
        CloseViewFlight = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FLIGHT ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 130, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FLIGHT NAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 180, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SOURCE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 230, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DEPARTURE TIME");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 290, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DEPARTURE DATE");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 330, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ARRIVE TIME");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(660, 260, 130, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DESTINATION");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(650, 100, 140, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ARRIVE DATE");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(650, 150, 140, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("FLIGHT CHARGES");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(660, 210, 130, 30);

        flight_ID.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        flight_ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flight_ID);
        flight_ID.setBounds(180, 130, 230, 30);

        flight_Source.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        flight_Source.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flight_Source);
        flight_Source.setBounds(180, 230, 230, 30);

        flight_DepTime.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        flight_DepTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flight_DepTime);
        flight_DepTime.setBounds(180, 280, 230, 30);

        flight_ArriveTime.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        flight_ArriveTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flight_ArriveTime);
        flight_ArriveTime.setBounds(810, 260, 230, 30);

        flight_Destination.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        flight_Destination.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flight_Destination);
        flight_Destination.setBounds(810, 100, 230, 30);

        flight_Charges.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        flight_Charges.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flight_Charges);
        flight_Charges.setBounds(810, 210, 230, 30);

        flight_Name.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        flight_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(flight_Name);
        flight_Name.setBounds(180, 180, 230, 30);

        flight_arriveDate.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel1.add(flight_arriveDate);
        flight_arriveDate.setBounds(810, 150, 230, 30);

        flight_DepDate.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel1.add(flight_DepDate);
        flight_DepDate.setBounds(180, 330, 230, 30);

        SearchByIDButton.setBackground(new java.awt.Color(95, 174, 201));
        SearchByIDButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchByIDButton.setText("Search By ID");
        SearchByIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByIDButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchByIDButton);
        SearchByIDButton.setBounds(430, 130, 110, 30);

        SearchByNameButton.setBackground(new java.awt.Color(172, 212, 226));
        SearchByNameButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchByNameButton.setText("Search By Name");
        SearchByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByNameButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchByNameButton);
        SearchByNameButton.setBounds(430, 180, 130, 30);

        TableDisplayFlightByName.setBackground(new java.awt.Color(86, 119, 118));
        TableDisplayFlightByName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FLIGHT ID", "FLIGHT NAME", "SOURCE", "DEPARTURE TIME", "DEPARTURE DATE", "DESTINATION", "ARRIVE DATE", "FLIGHT CHARGES", "ARRIVE TIME"
            }
        ));
        TableDisplayFlightByName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDisplayFlightByNameMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableDisplayFlightByName);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 370, 1090, 170);

        CloseViewFlight.setBackground(new java.awt.Color(255, 0, 0));
        CloseViewFlight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CloseViewFlight.setText("CLOSE");
        CloseViewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseViewFlightActionPerformed(evt);
            }
        });
        jPanel1.add(CloseViewFlight);
        CloseViewFlight.setBounds(1000, 0, 100, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 93, 118));
        jLabel8.setText("SEARCH FLIGHT BY USING THE OPTIONS PROVIDED");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(44, 10, 630, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CHARIF\\Downloads\\phoyoprojectjava\\flightviewbackView.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableDisplayFlightByNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDisplayFlightByNameMouseClicked
        
    }//GEN-LAST:event_TableDisplayFlightByNameMouseClicked

    private void CloseViewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseViewFlightActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this,"Do you want to close View Flight session session ?"," Confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
       if(res == JOptionPane.YES_OPTION){
           // closing the system
           this.hide();
       } else if(res == JOptionPane.NO_OPTION || res == JOptionPane.CLOSED_OPTION){
           return;
       }
    }//GEN-LAST:event_CloseViewFlightActionPerformed

    private void SearchByIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByIDButtonActionPerformed
        // TODO add your handling code here:
        try
            {
                jScrollPane2.setVisible(false);
                getContentPane().validate();
            
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");
                
                try
                {
                    String query="select * from flights where flightID=?";
                    pst=con.prepareStatement(query);
                   
                    pst.setString(1,flight_ID.getText());
                    ResultSet rs=pst.executeQuery();
                     if(rs.next())
                    {
                    
                 String F_Name = rs.getString("flightName");
                 String F_Source = rs.getString("flightsource");
                 String F_depTime = rs.getString("departureTime");
                 
                  String F_depDate = rs.getString("departureDate");
                Date depDate = new SimpleDateFormat("dd-MM-yyyy").parse(F_depDate); 
                                
                 String F_arrTime = rs.getString("arriveTime");
                  String F_destina = rs.getString("destination");
                  
                  String F_arrDate= rs.getString("arriveDate");
                Date arrDate = new SimpleDateFormat("dd-MM-yyyy").parse(F_arrDate); 
                String F_Charges = rs.getString("chargesFlight");
                
 //f_name,l_name,country,Gender,passport_number,expire_passport,contact,dob,address,photo                
                 flight_Name.setText(F_Name.trim());
                 flight_Source.setText(F_Source.trim());
                 flight_DepTime.setText(F_depTime.trim());
                 flight_DepDate.setDate(depDate);
                 flight_ArriveTime.setText(F_arrTime.trim());
                 flight_Destination.setText(F_destina.trim());
                 flight_arriveDate.setDate(arrDate);
                 flight_Charges.setText(F_Charges.trim());                  
                
                                   
                    }
                  else
                     {
                         JOptionPane.showMessageDialog(rootPane, "Wrong FLight ID Records ", " Error ",JOptionPane.ERROR_MESSAGE);
                     }
                
                     
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error in query due to "+e.getMessage(), " Error ",JOptionPane.ERROR_MESSAGE);
                }
                finally
                {
                    con.close();
                }
            }
        catch(Exception e)
        {
         e.printStackTrace();
         JOptionPane.showMessageDialog(rootPane, "Error in connection" +e.getMessage());
    }
    }//GEN-LAST:event_SearchByIDButtonActionPerformed

    private void SearchByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByNameButtonActionPerformed
        // TODO add your handling code here:
         try
            {
                
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");
                
                try
                {
                    
                    if(!flight_Name.getText().equals(""))
                    {
                    String q="select * from flights where flightName like ?";
                     pst=con.prepareStatement(q);
                    pst.setString(1,flight_Name.getText()+ "%");
                    ResultSet myresult=pst.executeQuery();
                     DefaultTableModel mymodel=(DefaultTableModel) TableDisplayFlightByName.getModel();
                     mymodel.setNumRows(0);
                      
                     if(myresult.next())
                    {
                        jScrollPane2.setVisible(true);
                      getContentPane().validate();
                        do
                        {                         
                         
                            String flightID = myresult.getString("flightID");
                            String flightname = myresult.getString("flightName");
                            String flightsource = myresult.getString("flightsource");
                            String flightdeptime = myresult.getString("departureTime");
                            String flightdepdate = myresult.getString("departureDate");
                            String flightdestination = myresult.getString("destination");
                            String arrivedate = myresult.getString("arriveDate");
                            String flightcharges = myresult.getString("chargesFlight");
                            String arrivetime = myresult.getString("arriveTime");                                                
                            
                            mymodel.addRow(new Object[]{flightID,flightname,flightsource,flightdeptime,flightdepdate,flightdestination,arrivedate,flightcharges,arrivetime});
                            
                            
                            
                        }
                        while(myresult.next());
                       
                           
                    }
                    else
                     {
                           jScrollPane2.setVisible(false);
                      getContentPane().validate();
                         JOptionPane.showMessageDialog(rootPane, "Wrong Flight Name or No Records", "Error",JOptionPane.ERROR_MESSAGE);
                     }
                    }
                 
                
                
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error in query due to "+e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
                }
                finally
                {
                    con.close();
                }
            }
        catch(Exception e)
        {
         e.printStackTrace();
         JOptionPane.showMessageDialog(rootPane, "Error in connection" +e.getMessage());
    }
    }//GEN-LAST:event_SearchByNameButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseViewFlight;
    private javax.swing.JButton SearchByIDButton;
    private javax.swing.JButton SearchByNameButton;
    private javax.swing.JTable TableDisplayFlightByName;
    private javax.swing.JTextField flight_ArriveTime;
    private javax.swing.JTextField flight_Charges;
    private com.toedter.calendar.JDateChooser flight_DepDate;
    private javax.swing.JTextField flight_DepTime;
    private javax.swing.JTextField flight_Destination;
    private javax.swing.JTextField flight_ID;
    private javax.swing.JTextField flight_Name;
    private javax.swing.JTextField flight_Source;
    private com.toedter.calendar.JDateChooser flight_arriveDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
