/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinereservation;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author CHARIF
 */
public class ViewCustomer extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCustomer
     */
    public ViewCustomer() {
        initComponents();
    }
     PreparedStatement pst;
     Connection con;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PhotoCustomer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        custId = new javax.swing.JTextField();
        CustFName = new javax.swing.JTextField();
        Custlname = new javax.swing.JTextField();
        CustCountry = new javax.swing.JTextField();
        CustPassID = new javax.swing.JTextField();
        MaleButton = new javax.swing.JRadioButton();
        FemaleButton = new javax.swing.JRadioButton();
        SearchCustomerById = new javax.swing.JButton();
        SearchByNameButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDisplayCustomer = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CustContact = new javax.swing.JTextField();
        expireDate = new com.toedter.calendar.JDateChooser();
        CustBirth = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        CustomerAdresss = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("VIEW CUSTOMER");

        jPanel1.setBackground(new java.awt.Color(196, 240, 156));

        PhotoCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 3));
        PhotoCustomer.setPreferredSize(new java.awt.Dimension(120, 75));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Country");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Passport ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gender");

        custId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        CustFName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Custlname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        CustCountry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        CustPassID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        MaleButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MaleButton.setText("Male");

        FemaleButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FemaleButton.setText("Female");

        SearchCustomerById.setText("Search by ID");
        SearchCustomerById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCustomerByIdActionPerformed(evt);
            }
        });

        SearchByNameButton.setText("Search by Name");
        SearchByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByNameButtonActionPerformed(evt);
            }
        });

        TableDisplayCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUSTOMER ID", "First Name", "Last Name", "Country", "Gender", "Passport ID", "Passport Expire Date", "Birth Day", "Contact", "Address"
            }
        ));
        TableDisplayCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDisplayCustomerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableDisplayCustomer);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Birth Day");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Passport Expire");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Contact");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Address");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(174, 167, 101));
        jLabel11.setText("Search Customer By Using any of option provided");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(MaleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(FemaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(custId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustFName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Custlname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustCountry, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustPassID, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expireDate, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(CustContact)
                            .addComponent(CustomerAdresss)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchCustomerById, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchByNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PhotoCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CustBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(373, 373, 373))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchCustomerById, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(custId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchByNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(CustFName)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(PhotoCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Custlname, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(expireDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CustPassID, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CustContact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FemaleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CustomerAdresss, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MaleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableDisplayCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDisplayCustomerMouseClicked
        int column=0;
        int row=TableDisplayCustomer.getSelectedRow();

        String custid=TableDisplayCustomer.getValueAt(row, column).toString();
        try
        {
            
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");

            try
            {
                String q="select * from customer where Cust_ID=?";
                pst=con.prepareStatement(q);
               pst.setString(1,custid);
                ResultSet myresult=pst.executeQuery();
                if(myresult.next())
                {
                  
                    PhotoCustomer.setIcon(new ImageIcon(ImageIO.read(new File(myresult.getString("Cust_photo")))));
                    custId.setText(myresult.getString("Cust_ID"));
                    CustFName.setText(myresult.getString("Cust_fname"));
                    Custlname.setText(myresult.getString("Cust_lname"));
                    CustCountry.setText(myresult.getString("Country"));
                    CustPassID.setText(myresult.getString("Cust_passportid"));
                    if(myresult.getString("Cust_gender").equals("Male"))
                    {
                        MaleButton.setSelected(true);
                    }
                    else
                    {
                        FemaleButton.setSelected(true);
                    }
                    CustBirth.setDate(myresult.getDate("Cust_birth"));
                    expireDate.setDate(myresult.getDate("Cust_expirepassport"));
                    CustContact.setText(myresult.getString("Cust_contact"));
                    CustomerAdresss.setText(myresult.getString("Cust_address"));
                   
                }

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error in query due to"+e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
            }
            finally
            {
                con.close();
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error in connection" +e.getMessage());
        }

    }//GEN-LAST:event_TableDisplayCustomerMouseClicked

    private void SearchByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByNameButtonActionPerformed
        // TODO add your handling code here:
        try
            {
                
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");
                
                try
                {
                    
                    if(!CustFName.getText().equals(""))
                    {
                    String q="select * from customer where Cust_fname like ?";
                     pst=con.prepareStatement(q);
                    pst.setString(1,CustFName.getText()+ "%");
                    ResultSet myresult=pst.executeQuery();
                     DefaultTableModel mymodel=(DefaultTableModel) TableDisplayCustomer.getModel();
                     mymodel.setNumRows(0);
                      
                     if(myresult.next())
                    {
                        jScrollPane2.setVisible(true);
                      getContentPane().validate();
                        do
                        {
//,,,,,,,,,Cust_photo                            
                            String custid=myresult.getString("Cust_ID");
                            String custfname=myresult.getString("Cust_fname");
                            String custlname = myresult.getString("Cust_lname");
                            String custcountry = myresult.getString("Country");
                            String gender=myresult.getString("Cust_gender");
                            String passID = myresult.getString("Cust_passportid");
                            String passExpire = myresult.getString("Cust_expirepassport");
                            String custbirth = myresult.getString("Cust_birth");
                            String custcontact = myresult.getString("Cust_contact");
                            String address=myresult.getString("Cust_address");
                            
                           //  PhotoCustomer.setIcon(new ImageIcon(ImageIO.read(new File(myresult.getString("Cust_photo")))));
                            
                            mymodel.addRow(new Object[]{custid,custfname,custlname,custcountry,gender,passID,passExpire,custbirth,custcontact,address});
                            
                            
                            
                        }
                        while(myresult.next());
                       
                           
                    }
                    else
                     {
                           jScrollPane2.setVisible(false);
                      getContentPane().validate();
                         JOptionPane.showMessageDialog(rootPane, "Wrong Customer Name/No Records", "Error",JOptionPane.ERROR_MESSAGE);
                     }
                    }
                 
                
                
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error in query due to "+e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
                }
                finally
                {
                    con.close();
                }
            }
        catch(Exception e)
        {
         e.printStackTrace();
         JOptionPane.showMessageDialog(rootPane, "Error in connection" +e.getMessage());
    }
    }//GEN-LAST:event_SearchByNameButtonActionPerformed

    private void SearchCustomerByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCustomerByIdActionPerformed
        // TODO add your handling code here:
        try
        {
            

            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");

            try
            {
                String query="select * from customer where Cust_ID=?";
                pst=con.prepareStatement(query);

                pst.setString(1,custId.getText());
                ResultSet rs=pst.executeQuery();
                if(rs.next())
                {

                    String F_Name = rs.getString("Cust_fname");
                    String l_Name = rs.getString("Cust_lname");
                    String Countr = rs.getString("Country");

                    String gender = rs.getString("Cust_gender");
                    String passId = rs.getString("Cust_passportid");
                    
                    String expirPass = rs.getString("Cust_expirepassport");
                    Date expDate = new SimpleDateFormat("dd-MM-yyyy").parse(expirPass);
                    
                    String birthCust= rs.getString("Cust_birth");
                    Date BirDate = new SimpleDateFormat("dd-MM-yyyy").parse(birthCust);
                    
                    String custCont = rs.getString("Cust_contact");
                    String custAddr = rs.getString("Cust_address");

                    java.sql.Blob blob = rs.getBlob("Cust_photo");
                byte[] _imagebytes = blob.getBytes(1,(int) blob.length());
                  ImageIcon image = new ImageIcon(_imagebytes);
                  Image im = image.getImage();
                  Image myImg = im.getScaledInstance(PhotoCustomer.getWidth(), PhotoCustomer.getHeight(), Image.SCALE_SMOOTH);
                  ImageIcon newImage = new ImageIcon(myImg);

                    
                    CustFName.setText(F_Name.trim());
                    Custlname.setText(l_Name.trim());
                    CustCountry.setText(Countr.trim());
                    CustPassID.setText(passId.trim());
                    if(gender.equals("Male")){
                        MaleButton.setSelected(true);
                        FemaleButton.setSelected(false);
                    } else {
                        FemaleButton.setSelected(true);
                        MaleButton.setSelected(false);
                    }
                   expireDate.setDate(expDate);
                   CustBirth.setDate(BirDate);
                   CustContact.setText(custCont.trim());
                   CustomerAdresss.setText(custAddr.trim());
                   PhotoCustomer.setIcon(newImage);
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Wrong FLight ID Records ", " Error ",JOptionPane.ERROR_MESSAGE);
                }

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error in query due to "+e.getMessage(), " Error ",JOptionPane.ERROR_MESSAGE);
            }
            finally
            {
                con.close();
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error in connection" +e.getMessage());
        }
    }//GEN-LAST:event_SearchCustomerByIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CustBirth;
    private javax.swing.JTextField CustContact;
    private javax.swing.JTextField CustCountry;
    private javax.swing.JTextField CustFName;
    private javax.swing.JTextField CustPassID;
    private javax.swing.JTextField Custlname;
    private javax.swing.JTextField CustomerAdresss;
    private javax.swing.JRadioButton FemaleButton;
    private javax.swing.JRadioButton MaleButton;
    private javax.swing.JLabel PhotoCustomer;
    private javax.swing.JButton SearchByNameButton;
    private javax.swing.JButton SearchCustomerById;
    private javax.swing.JTable TableDisplayCustomer;
    private javax.swing.JTextField custId;
    private com.toedter.calendar.JDateChooser expireDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
